channels:
- conda-forge
dependencies:
- nbsphinx
- sphinx
- sphinx_rtd_theme
- myst-parser
- numpy
- openmpi
- cloudpickle =3.0.0
- mpi4py =3.1.6
- tqdm =4.66.2
- pyzmq =26.0.2
- flux-core
- jupyter-book =1.0.0
