channels:
- conda-forge
dependencies:
- python
- numpy
- openmpi =4.1.4
- cloudpickle =2.0.0
- conda_subprocess =0.0.3
- mpi4py =3.1.4
- pyzmq =25.0.0
- h5py =3.6.0
- matplotlib =3.5.3
- networkx =2.8.8
- ipython =7.33.0
- pygraphviz =1.10
