channels:
- conda-forge
dependencies:
- python
- numpy
- msmpi
- cloudpickle =3.1.0
- mpi4py =4.0.1
- pyzmq =26.2.0
- h5py =3.12.1
- matplotlib =3.9.2
- networkx =3.4.1
- pygraphviz =1.14
- ipython =8.28.0
