channels:
- conda-forge
dependencies:
- python
- numpy
- msmpi
- cloudpickle =3.0.0
- conda_subprocess =0.0.4
- mpi4py =4.0.0
- pyzmq =26.2.0
- h5py =3.11.0
- h5io =0.2.4
- matplotlib =3.9.2
- networkx =3.3
- pygraphviz =1.13
- ipython =8.26.0
