channels:
- conda-forge
dependencies:
- h5py =3.15.1
- jupyter
- mpi4py =4.1.1
- numpy =2.4.1
- openmpi
- papermill
- atomistics =0.3.4
- cloudpickle =3.1.2
- flux-core =0.81.0
- flux-pmix =0.6.0
- gpaw =25.7.0
- hatchling =1.28.0
- hatch-vcs =0.5.0
- ipython =9.9.0
- matplotlib =3.10.8
- networkx =3.6.1
- pygraphviz =1.14
- pysqa =0.3.4
- pyzmq =27.1.0
- qe =7.5
