channels:
- conda-forge
dependencies:
- flux-core
- hatchling
- hatch-vcs
- myst-parser
- nbsphinx
- numpy
- openmpi
- sphinx
- sphinx_rtd_theme
- cloudpickle =3.1.2
- h5py =3.15.1
- jupyter-book =1.0.0
- mpi4py =4.1.1
- python =3.12
- pydantic =2.12.4
- pyzmq =27.1.0
