channels:
- conda-forge
dependencies:
- python
- numpy =2.4.1
- openmpi
- cloudpickle =3.1.2
- h5py =3.15.1
- hatchling =1.28.0
- hatch-vcs =0.5.0
- ipython =9.9.0
- mpi4py =4.1.1
- networkx =3.6.1
- pygraphviz =1.14
- pysqa =0.3.4
- pyzmq =27.1.0
